2025-10-28 11:11:37,951 INFO    MainThread:6363 [wandb_setup.py:_flush():81] Current SDK version is 0.22.2
2025-10-28 11:11:37,951 INFO    MainThread:6363 [wandb_setup.py:_flush():81] Configure stats pid to 6363
2025-10-28 11:11:37,951 INFO    MainThread:6363 [wandb_setup.py:_flush():81] Loading settings from /home/bhavani/.config/wandb/settings
2025-10-28 11:11:37,951 INFO    MainThread:6363 [wandb_setup.py:_flush():81] Loading settings from /home/bhavani/Desktop/sem_7/MLOps/mlops2025w_112201026/Class/week10/wandb/settings
2025-10-28 11:11:37,951 INFO    MainThread:6363 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-10-28 11:11:37,951 INFO    MainThread:6363 [wandb_init.py:setup_run_log_directory():705] Logging user logs to /home/bhavani/Desktop/sem_7/MLOps/mlops2025w_112201026/Class/week10/wandb/run-20251028_111137-mww4o0ll/logs/debug.log
2025-10-28 11:11:37,952 INFO    MainThread:6363 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to /home/bhavani/Desktop/sem_7/MLOps/mlops2025w_112201026/Class/week10/wandb/run-20251028_111137-mww4o0ll/logs/debug-internal.log
2025-10-28 11:11:37,952 INFO    MainThread:6363 [wandb_init.py:monkeypatch_ipython():624] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fe114112110>
2025-10-28 11:11:37,952 INFO    MainThread:6363 [wandb_init.py:init():832] calling init triggers
2025-10-28 11:11:37,952 INFO    MainThread:6363 [wandb_init.py:init():837] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-10-28 11:11:37,952 INFO    MainThread:6363 [wandb_init.py:init():880] starting backend
2025-10-28 11:11:38,164 INFO    MainThread:6363 [wandb_init.py:init():883] sending inform_init request
2025-10-28 11:11:38,170 INFO    MainThread:6363 [wandb_init.py:init():891] backend started and connected
2025-10-28 11:11:38,176 INFO    MainThread:6363 [wandb_run.py:_label_probe_notebook():1330] probe notebook
2025-10-28 11:11:38,177 INFO    MainThread:6363 [wandb_run.py:_label_probe_notebook():1340] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-10-28 11:11:38,178 INFO    MainThread:6363 [wandb_init.py:init():961] updated telemetry
2025-10-28 11:11:38,186 INFO    MainThread:6363 [wandb_init.py:init():985] communicating run to backend with 90.0 second timeout
2025-10-28 11:11:39,046 INFO    MainThread:6363 [wandb_init.py:init():1036] starting run threads in backend
2025-10-28 11:11:39,397 INFO    MainThread:6363 [wandb_run.py:_console_start():2509] atexit reg
2025-10-28 11:11:39,397 INFO    MainThread:6363 [wandb_run.py:_redirect():2357] redirect: wrap_raw
2025-10-28 11:11:39,397 INFO    MainThread:6363 [wandb_run.py:_redirect():2426] Wrapping output streams.
2025-10-28 11:11:39,397 INFO    MainThread:6363 [wandb_run.py:_redirect():2449] Redirects installed.
2025-10-28 11:11:39,399 INFO    MainThread:6363 [wandb_init.py:init():1076] run started, returning control to user process
2025-10-28 11:11:39,400 INFO    MainThread:6363 [wandb_run.py:_config_callback():1392] config_cb None None {'n_estimators': 50, 'random_state': 42}
2025-10-28 11:11:42,220 INFO    MainThread:6363 [wandb_run.py:_finish():2275] finishing run 112201026-indian-institute-of-technology-palakkad/mlops-performance-monitoring/mww4o0ll
2025-10-28 11:11:42,221 INFO    MainThread:6363 [jupyter.py:save_history():480] not saving jupyter history
2025-10-28 11:11:42,221 INFO    MainThread:6363 [jupyter.py:save_ipynb():404] not saving jupyter notebook
2025-10-28 11:11:42,221 INFO    MainThread:6363 [wandb_init.py:_jupyter_teardown():609] cleaning up jupyter logic
2025-10-28 11:11:42,221 INFO    MainThread:6363 [wandb_run.py:_atexit_cleanup():2474] got exitcode: 0
2025-10-28 11:11:42,222 INFO    MainThread:6363 [wandb_run.py:_restore():2456] restore
2025-10-28 11:11:42,222 INFO    MainThread:6363 [wandb_run.py:_restore():2462] restore done
2025-10-28 11:11:45,636 INFO    MainThread:6363 [wandb_run.py:_footer_sync_info():3872] logging synced files
